spring.application.name=bank-account-customer-mgmt
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:h2:F:/FDMGroup/Temp/Spring-Database/Account-Customer-DB;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

logging.file.name=myapp.log