spring.application.name=bank-account-customer-mgmt
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.h2.Driver

logging.file.name=myapp.log